export const C = {
  bgGrad:     'linear-gradient(160deg,#4a7a7a 0%,#2d5555 20%,#1a3535 50%,#8a5030 80%,#b07040 100%)',
  card:       'rgba(20,52,52,0.90)',
  cardBorder: 'rgba(180,210,200,0.18)',
  tealLight:  'rgba(60,110,100,0.55)',
  gold:       '#c8901a',
  goldLight:  'rgba(200,144,26,0.18)',
  goldBright: '#e0aa30',
  text:       '#e8f0ec',
  textMuted:  'rgba(220,240,230,0.5)',
  font:       "'Georgia','Times New Roman',serif",
  green:      'rgba(30,140,80,0.6)',
  greenBorder:'rgba(50,200,100,0.35)',
}

export const VERSICULOS = [
  { ref:'Juan 3:16', text:'Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.' },
  { ref:'Salmos 23:1', text:'Jehová es mi pastor; nada me faltará.' },
  { ref:'Filipenses 4:13', text:'Todo lo puedo en Cristo que me fortalece.' },
  { ref:'Jeremías 29:11', text:'Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.' },
  { ref:'Proverbios 3:5-6', text:'Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia. Reconócele en todos tus caminos, y él enderezará tus veredas.' },
  { ref:'Mateo 11:28', text:'Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.' },
  { ref:'Romanos 8:28', text:'Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien.' },
  { ref:'Isaías 40:31', text:'Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas.' },
  { ref:'Josué 1:9', text:'Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo.' },
  { ref:'Salmos 46:1', text:'Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.' },
  { ref:'Gálatas 2:20', text:'Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí.' },
  { ref:'Mateo 6:33', text:'Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.' },
  { ref:'2 Corintios 5:17', text:'De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.' },
  { ref:'Juan 14:6', text:'Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.' },
  { ref:'Salmos 119:105', text:'Lámpara es a mis pies tu palabra, y lumbrera a mi camino.' },
  { ref:'Efesios 2:8-9', text:'Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios.' },
  { ref:'Apocalipsis 3:20', text:'He aquí, yo estoy a la puerta y llamo; si alguno oye mi voz y abre la puerta, entraré a él.' },
  { ref:'Romanos 10:9', text:'Que si confesares con tu boca que Jesús es el Señor, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo.' },
  { ref:'1 Juan 4:19', text:'Nosotros le amamos a él, porque él nos amó primero.' },
  { ref:'Hebreos 11:1', text:'Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve.' },
  { ref:'Lamentaciones 3:22-23', text:'Por la misericordia de Jehová no hemos sido consumidos. Nuevas son cada mañana; grande es tu fidelidad.' },
  { ref:'Salmos 37:4', text:'Deléitate asimismo en Jehová, y él te concederá las peticiones de tu corazón.' },
  { ref:'Filipenses 4:6-7', text:'Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias.' },
  { ref:'Juan 10:10', text:'Yo he venido para que tengan vida, y para que la tengan en abundancia.' },
  { ref:'Miqueas 6:8', text:'Solamente hacer justicia, y amar misericordia, y humillarte ante tu Dios.' },
  { ref:'Números 6:24-26', text:'Jehová te bendiga, y te guarde; Jehová haga resplandecer su rostro sobre ti, y tenga de ti misericordia.' },
  { ref:'Mateo 28:19-20', text:'Id, y haced discípulos a todas las naciones. Y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo.' },
  { ref:'Salmos 91:1-2', text:'El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.' },
  { ref:'Proverbios 18:10', text:'Torre fuerte es el nombre de Jehová; a él correrá el justo, y será levantado.' },
  { ref:'Romanos 8:38-39', text:'Estoy seguro de que ni la muerte, ni la vida, ni ángeles, ni principados podrá separarnos del amor de Dios.' },
]

export const CURIOSIDADES = [
  'La Biblia fue escrita por más de 40 autores durante aproximadamente 1.600 años, en hebreo, arameo y griego.',
  "La palabra 'Biblia' viene del griego 'biblia', que significa 'libros'. Es una biblioteca de 66 libros.",
  'El libro de Ester no menciona directamente el nombre de Dios en ninguno de sus versículos.',
  'Matusalén vivió 969 años, siendo el hombre más longevo registrado en la Biblia (Génesis 5:27).',
  "El versículo más corto de la Biblia es Juan 11:35: 'Jesús lloró.'",
  'Los Salmos tiene 150 capítulos. El capítulo 117 es el más corto y el 119 el más largo de toda la Biblia.',
  "El nombre 'Jehová' aparece más de 6.800 veces en el Antiguo Testamento (Reina Valera 1960).",
  'La Biblia es el libro más vendido de la historia, con más de 5.000 millones de copias distribuidas.',
  'Jesús realizó su primer milagro en las bodas de Caná, convirtiendo agua en vino (Juan 2:1-11).',
  'El libro de Proverbios fue escrito principalmente por Salomón, considerado el hombre más sabio.',
  'El río Jordán aparece mencionado más de 175 veces en la Biblia. Jesús fue bautizado en sus aguas.',
  'Abraham tenía 75 años cuando Dios le llamó a dejar su tierra y partir hacia Canaán (Génesis 12:4).',
  'El apóstol Pablo escribió 13 de los 27 libros del Nuevo Testamento.',
  'David escribió al menos 73 de los 150 salmos del libro de los Salmos.',
  'Moisés escribió los primeros cinco libros de la Biblia, conocidos como el Pentateuco.',
  'El libro de Apocalipsis fue escrito por Juan mientras estaba exiliado en la isla de Patmos.',
  'La Biblia menciona más de 40 tipos diferentes de animales, desde leones hasta hormigas.',
  'Salomón tuvo 700 esposas y 300 concubinas según 1 Reyes 11:3.',
  'Noé tenía 600 años cuando comenzó el diluvio universal (Génesis 7:6).',
  'El mar de Galilea, también llamado lago de Genesaret, aparece en muchos milagros de Jesús.',
]

export const TEMAS = [
  { icon:'📜', label:'Profetas', items:['Isaías — El evangelio del AT','Jeremías — El profeta llorón','Ezequiel — Visiones de gloria','Daniel — Fe en el exilio','Amós — Justicia social','Oseas — Amor fiel','Miqueas — Justicia y misericordia','Zacarías — Profecías mesiánicas','Malaquías — El último profeta'] },
  { icon:'🎵', label:'Salmos', items:['Salmo 1 — El justo y el impío','Salmo 23 — Jehová mi pastor','Salmo 51 — Arrepentimiento','Salmo 91 — Amparo del Altísimo','Salmo 103 — Bendice alma mía','Salmo 119 — La Palabra de Dios','Salmo 121 — Mi socorro','Salmo 139 — Dios todo lo sabe'] },
  { icon:'✨', label:'Milagros', items:['Bodas de Caná — Agua en vino','Multiplicación de los panes','Caminó sobre el agua','Sanó al ciego de nacimiento','Resucitó a Lázaro','Curó al paralítico','Calmó la tempestad'] },
  { icon:'🙏', label:'Parábolas', items:['El Hijo Pródigo (Lucas 15)','El Buen Samaritano (Lucas 10)','La Oveja Perdida (Lucas 15)','Los Talentos (Mateo 25)','El Sembrador (Mateo 13)','Las Diez Vírgenes (Mateo 25)'] },
  { icon:'👑', label:'Reyes', items:['Saúl — El primer rey','David — El rey pastor','Salomón — Rey sabio','Roboam — División del reino','Ezequías — Rey piadoso','Josías — El rey reformador'] },
  { icon:'📖', label:'Evangelios', items:['Mateo — El Rey Mesías','Marcos — El Siervo activo','Lucas — Hijo del Hombre','Juan — Hijo de Dios','El Sermón del Monte','La Última Cena','La Resurrección'] },
  { icon:'⚓', label:'Héroes', items:['Abraham — Padre de la fe','Moisés — Libertador','José — De esclavo a gobernador','Rut — Fidelidad y redención','Ester — Valor ante el rey','Nehemías — Constructor','Pablo — De perseguidor a apóstol'] },
  { icon:'🕊️', label:'Espíritu Santo', items:['Pentecostés — Hechos 2','Frutos del Espíritu (Gálatas 5)','Dones espirituales (1 Cor 12)','La paloma en el bautismo','El Consolador (Juan 14)'] },
]

export const ALABANZAS_SUGERIDAS = [
  { titulo:'Renuévame', artista:'Marcos Witt', query:'Marcos Witt Renuévame' },
  { titulo:'Cuán grande es Él', artista:'Hillsong', query:'Hillsong Cuán grande es Él español' },
  { titulo:'Oceans (Océanos)', artista:'Hillsong United', query:'Hillsong United Océanos español' },
  { titulo:'Way Maker', artista:'Sinach', query:'Way Maker Sinach español' },
  { titulo:'Eres Todo Poderoso', artista:'Generación 12', query:'Generación 12 Eres Todo Poderoso' },
  { titulo:'10,000 Razones', artista:'Matt Redman', query:'10000 Razones Matt Redman español' },
  { titulo:'Soy Libre', artista:'Hillsong', query:'Hillsong Soy Libre' },
  { titulo:'Te Alabo', artista:'Jesús Adrián Romero', query:'Jesús Adrián Romero Te Alabo' },
  { titulo:'Sublime Gracia', artista:'Tradicional', query:'Sublime Gracia himno cristiano' },
  { titulo:'Buen Pastor', artista:'Elevation Worship', query:'Elevation Worship Buen Pastor español' },
  { titulo:'Sé Tú Mi Visión', artista:'Tradicional', query:'Sé Tú Mi Visión himno cristiano' },
  { titulo:'Poderoso Eres Tú', artista:'Marcos Witt', query:'Marcos Witt Poderoso Eres Tú' },
  { titulo:'Dios de lo Imposible', artista:'Generación 12', query:'Generación 12 Dios de lo Imposible' },
  { titulo:'Glorioso', artista:'Marcos Witt', query:'Marcos Witt Glorioso' },
  { titulo:'Rey de Reyes', artista:'Hillsong', query:'Hillsong Rey de Reyes español' },
  { titulo:'El Poder de Tu Amor', artista:'Geoff Bullock', query:'El Poder de Tu Amor cristiano' },
]
