export const C = {
  bg: `linear-gradient(175deg,
    #0d4a52 0%, #1a6868 12%, #2a8870 22%,
    #4a7858 32%, #8a5030 50%,
    #c85520 65%, #e06828 78%,
    #f08038 88%, #f8a050 100%)`,
  teal:     '#1a6868',
  tealD:    '#0d3a42',
  coral:    '#c85520',
  coralB:   '#e87030',
  gold:     '#f09050',
  goldB:    '#ffc070',
  text:     '#fff5ee',
  textMuted:'rgba(255,235,210,0.55)',
  font:     "'Georgia','Times New Roman',serif",
  cardBdr:  'rgba(240,160,80,0.30)',
  card:     'rgba(8,35,42,0.88)',
  green:    'rgba(20,120,70,0.65)',
  greenBdr: 'rgba(40,200,100,0.3)',
}

export const VERSICULOS = [
  { ref:'Juan 3:16', text:'Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.' },
  { ref:'Salmos 23:1', text:'Jehová es mi pastor; nada me faltará.' },
  { ref:'Filipenses 4:13', text:'Todo lo puedo en Cristo que me fortalece.' },
  { ref:'Jeremías 29:11', text:'Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.' },
  { ref:'Proverbios 3:5-6', text:'Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia. Reconócele en todos tus caminos, y él enderezará tus veredas.' },
  { ref:'Mateo 11:28', text:'Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.' },
  { ref:'Romanos 8:28', text:'Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien.' },
  { ref:'Isaías 40:31', text:'Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas.' },
  { ref:'Josué 1:9', text:'Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo.' },
  { ref:'Salmos 46:1', text:'Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.' },
  { ref:'Gálatas 2:20', text:'Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí.' },
  { ref:'Mateo 6:33', text:'Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.' },
  { ref:'2 Corintios 5:17', text:'De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.' },
  { ref:'Juan 14:6', text:'Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.' },
  { ref:'Salmos 119:105', text:'Lámpara es a mis pies tu palabra, y lumbrera a mi camino.' },
  { ref:'Efesios 2:8-9', text:'Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios.' },
  { ref:'Apocalipsis 3:20', text:'He aquí, yo estoy a la puerta y llamo; si alguno oye mi voz y abre la puerta, entraré a él.' },
  { ref:'Romanos 10:9', text:'Que si confesares con tu boca que Jesús es el Señor, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo.' },
  { ref:'1 Juan 4:19', text:'Nosotros le amamos a él, porque él nos amó primero.' },
  { ref:'Hebreos 11:1', text:'Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve.' },
  { ref:'Lamentaciones 3:22-23', text:'Por la misericordia de Jehová no hemos sido consumidos. Nuevas son cada mañana; grande es tu fidelidad.' },
  { ref:'Salmos 37:4', text:'Deléitate asimismo en Jehová, y él te concederá las peticiones de tu corazón.' },
  { ref:'Filipenses 4:6-7', text:'Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias.' },
  { ref:'Juan 10:10', text:'Yo he venido para que tengan vida, y para que la tengan en abundancia.' },
  { ref:'Miqueas 6:8', text:'Solamente hacer justicia, y amar misericordia, y humillarte ante tu Dios.' },
  { ref:'Números 6:24-26', text:'Jehová te bendiga, y te guarde; Jehová haga resplandecer su rostro sobre ti, y tenga de ti misericordia.' },
  { ref:'Mateo 28:19-20', text:'Id, y haced discípulos a todas las naciones. Y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo.' },
  { ref:'Salmos 91:1-2', text:'El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.' },
  { ref:'Proverbios 18:10', text:'Torre fuerte es el nombre de Jehová; a él correrá el justo, y será levantado.' },
  { ref:'Romanos 8:38-39', text:'Estoy seguro de que ni la muerte, ni la vida, ni ángeles, ni principados podrá separarnos del amor de Dios.' },
]

export const CURIOSIDADES = [
  'La Biblia fue escrita por más de 40 autores durante aproximadamente 1.600 años, en hebreo, arameo y griego.',
  "La palabra 'Biblia' viene del griego 'biblia', que significa 'libros'. Es una biblioteca de 66 libros.",
  'El libro de Ester no menciona directamente el nombre de Dios en ninguno de sus versículos.',
  'Matusalén vivió 969 años, siendo el hombre más longevo registrado en la Biblia (Génesis 5:27).',
  "El versículo más corto de la Biblia es Juan 11:35: 'Jesús lloró.'",
  'Los Salmos tiene 150 capítulos. El capítulo 117 es el más corto y el 119 el más largo de toda la Biblia.',
  "El nombre 'Jehová' aparece más de 6.800 veces en el Antiguo Testamento (Reina Valera 1960).",
  'La Biblia es el libro más vendido de la historia, con más de 5.000 millones de copias distribuidas.',
  'Jesús realizó su primer milagro en las bodas de Caná, convirtiendo agua en vino (Juan 2:1-11).',
  'El libro de Proverbios fue escrito principalmente por Salomón, considerado el hombre más sabio.',
  'El río Jordán aparece mencionado más de 175 veces en la Biblia. Jesús fue bautizado en sus aguas.',
  'Abraham tenía 75 años cuando Dios le llamó a dejar su tierra y partir hacia Canaán (Génesis 12:4).',
  'El apóstol Pablo escribió 13 de los 27 libros del Nuevo Testamento.',
  'David escribió al menos 73 de los 150 salmos del libro de los Salmos.',
  'Moisés escribió los primeros cinco libros de la Biblia, conocidos como el Pentateuco.',
  'El libro de Apocalipsis fue escrito por Juan mientras estaba exiliado en la isla de Patmos.',
  'La Biblia menciona más de 40 tipos diferentes de animales, desde leones hasta hormigas.',
  'Salomón tuvo 700 esposas y 300 concubinas según 1 Reyes 11:3.',
  'Noé tenía 600 años cuando comenzó el diluvio universal (Génesis 7:6).',
  'El mar de Galilea, también llamado lago de Genesaret, aparece en muchos milagros de Jesús.',
]

export const TEMAS_DETALLE = {
  Profetas: [
    { nombre:'Isaías', ref:'Isaías 7:14', txt:'He aquí que la virgen concebirá, y dará a luz un hijo, y llamará su nombre Emanuel.', desc:'Llamado el "Evangelio del Antiguo Testamento". Profetizó la venida del Mesías con gran detalle. Ministerio: ~740–680 a.C. en Judá.' },
    { nombre:'Jeremías', ref:'Jeremías 29:11', txt:'Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal.', desc:'El profeta llorón. Anunció la cautividad babilónica y el nuevo pacto (Jer 31:31-34). Ministerio: ~627–586 a.C.' },
    { nombre:'Ezequiel', ref:'Ezequiel 36:26', txt:'Os daré corazón nuevo y pondré espíritu nuevo dentro de vosotros; y quitaré de vuestra carne el corazón de piedra.', desc:'Profetizó entre los cautivos en Babilonia. Sus visiones incluyen el valle de los huesos secos y el templo glorioso del futuro.' },
    { nombre:'Daniel', ref:'Daniel 1:8', txt:'Y Daniel propuso en su corazón no contaminarse con la porción de la comida del rey, ni con el vino que él bebía.', desc:'Fidelidad absoluta en el exilio. Interpretó sueños del rey, sobrevivió el foso de leones y recibió visiones proféticas del fin.' },
    { nombre:'Amós', ref:'Amós 5:24', txt:'Pero corra el juicio como las aguas, y la justicia como impetuoso arroyo.', desc:'Pastor de Tecoa. Profetizó justicia social contra Israel y las naciones vecinas. Siglo VIII a.C. Libro de gran vigencia social.' },
    { nombre:'Oseas', ref:'Oseas 6:6', txt:'Porque misericordia quiero y no sacrificio, y conocimiento de Dios más que holocaustos.', desc:'Su matrimonio con Gomer simbolizó el amor fiel de Dios a Israel infiel. Profetizó en el reino del norte (~750–710 a.C.).' },
    { nombre:'Miqueas', ref:'Miqueas 6:8', txt:'Solamente hacer justicia, y amar misericordia, y humillarte ante tu Dios.', desc:'Profetizó el nacimiento del Mesías en Belén (Miq 5:2). Contemporáneo de Isaías. Defensor de los pobres ante los poderosos.' },
    { nombre:'Zacarías', ref:'Zacarías 9:9', txt:'He aquí tu rey vendrá a ti, justo y salvador, humilde, y cabalgando sobre un asno.', desc:'Profetizó la entrada triunfal de Jesús en Jerusalén y detalles de la pasión. Período postexílico, ~520 a.C.' },
    { nombre:'Malaquías', ref:'Malaquías 3:1', txt:'He aquí, yo envío mi mensajero, el cual preparará el camino delante de mí.', desc:'Último profeta del AT antes de 400 años de silencio. Anunció a Juan el Bautista como el mensajero que prepararía el camino.' },
  ],
  Salmos: [
    { nombre:'Salmo 1', ref:'Salmos 1:1-2', txt:'Bienaventurado el varón que no anduvo en consejo de malos... sino que en la ley de Jehová está su delicia.', desc:'El salmo de los dos caminos: el del justo que medita en la Palabra y el del impío que perece. Introducción al Salterio.' },
    { nombre:'Salmo 23', ref:'Salmos 23:1-3', txt:'Jehová es mi pastor; nada me faltará. En lugares de delicados pastos me hará descansar.', desc:'El salmo del buen pastor. David expresa confianza plena en la provisión y guía de Dios en cada momento de la vida.' },
    { nombre:'Salmo 51', ref:'Salmos 51:10', txt:'Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.', desc:'Salmo de arrepentimiento de David tras su pecado con Betsabé. Modelo de confesión, humildad y restauración ante Dios.' },
    { nombre:'Salmo 91', ref:'Salmos 91:1-2', txt:'El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.', desc:'Promesas de protección divina. Amparo para quien confía en Dios en tiempos de peligro, enfermedad y tribulación.' },
    { nombre:'Salmo 103', ref:'Salmos 103:2-3', txt:'Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios. Él es quien perdona todas tus iniquidades.', desc:'Canto de alabanza por las misericordias de Dios: perdón, sanidad, redención y amor eterno que alcanza a sus hijos.' },
    { nombre:'Salmo 119', ref:'Salmos 119:105', txt:'Lámpara es a mis pies tu palabra, y lumbrera a mi camino.', desc:'El salmo más largo con 176 versículos en 22 secciones (letras hebreas). Exalta la Palabra de Dios como guía perfecta.' },
    { nombre:'Salmo 121', ref:'Salmos 121:1-2', txt:'Alzaré mis ojos a los montes; ¿de dónde vendrá mi socorro? Mi socorro viene de Jehová.', desc:'Cántico de los peregrinos. La protección constante de Dios día y noche, en el camino y en el destino de la vida.' },
    { nombre:'Salmo 139', ref:'Salmos 139:14', txt:'Te alabaré; porque formidables, maravillosas son tus obras; estoy maravillado, y mi alma lo sabe muy bien.', desc:'Dios lo conoce todo de nosotros. Omnisciencia, omnipresencia y amor creador de Dios hacia cada persona.' },
  ],
  Milagros: [
    { nombre:'Agua en vino', ref:'Juan 2:11', txt:'Este principio de señales hizo Jesús en Caná de Galilea, y manifestó su gloria; y sus discípulos creyeron en él.', desc:'Primer milagro de Jesús en las bodas de Caná. A petición de María convirtió 6 tinajas de agua en vino excelente.' },
    { nombre:'Multiplicación', ref:'Juan 6:11', txt:'Y Jesús tomó aquellos panes, y habiendo dado gracias, los repartió entre los discípulos... asimismo de los peces.', desc:'Con 5 panes y 2 peces alimentó a más de 5.000 personas. Señal de que Jesús es el Pan de Vida que sacia el alma.' },
    { nombre:'Caminó sobre el mar', ref:'Mateo 14:27', txt:'Pero en seguida Jesús les habló, diciendo: ¡Tened ánimo; yo soy, no temáis!', desc:'Jesús caminó sobre el mar de Galilea y extendió la mano a Pedro cuando éste comenzó a hundirse por la duda.' },
    { nombre:'Resucitó a Lázaro', ref:'Juan 11:43-44', txt:'Habiendo dicho esto, clamó a gran voz: ¡Lázaro, ven fuera! Y el que había muerto salió.', desc:'Cuatro días después de su muerte, Jesús resucitó a Lázaro. La mayor señal que prefiguró su propia resurrección.' },
    { nombre:'Sanó al ciego', ref:'Juan 9:3', txt:'No es que pecó éste, ni sus padres, sino para que las obras de Dios se manifiesten en él.', desc:'Jesús sanó a un hombre ciego de nacimiento. Usó barro hecho con saliva. Los fariseos rechazaron este milagro evidente.' },
    { nombre:'Curó al paralítico', ref:'Marcos 2:11-12', txt:'A ti te digo: Levántate, toma tu lecho, y vete a tu casa. Entonces él se levantó en seguida.', desc:'Cuatro amigos bajaron al paralítico por el techo ante Jesús. Jesús perdonó sus pecados y lo sanó completamente.' },
    { nombre:'Calmó la tempestad', ref:'Marcos 4:39', txt:'Y levantándose, reprendió al viento, y dijo al mar: Calla, enmudece. Y cesó el viento, y se hizo grande bonanza.', desc:'En el mar de Galilea Jesús reprendió la tormenta con una sola palabra, demostrando su señorío sobre la naturaleza.' },
  ],
  Parábolas: [
    { nombre:'El Hijo Pródigo', ref:'Lucas 15:20', txt:'Y cuando aún estaba lejos, lo vio su padre, y fue movido a misericordia, y corrió, y se echó sobre su cuello.', desc:'El amor incondicional del Padre. El hijo menor malgastó su herencia pero al regresar arrepentido fue recibido con fiesta.' },
    { nombre:'Buen Samaritano', ref:'Lucas 10:33-34', txt:'Pero un samaritano... viéndole, fue movido a misericordia; y acercándose, vendó sus heridas.', desc:'Respuesta a "¿Quién es mi prójimo?" El amor al prójimo no conoce fronteras de raza ni religión. Actuar como el samaritano.' },
    { nombre:'La Oveja Perdida', ref:'Lucas 15:5', txt:'Y cuando la encuentra, la pone sobre sus hombros gozoso; y al llegar a casa, convoca a sus amigos y vecinos.', desc:'Dios busca activamente a cada alma perdida. El gozo del cielo cuando un pecador se arrepiente es incomparable.' },
    { nombre:'Los Talentos', ref:'Mateo 25:21', txt:'Bien, buen siervo y fiel; sobre poco has sido fiel, sobre mucho te pondré; entra en el gozo de tu señor.', desc:'Responsabilidad con los dones dados por Dios. Seremos juzgados por el uso fiel de lo que Dios nos ha confiado.' },
    { nombre:'El Sembrador', ref:'Mateo 13:8', txt:'Pero parte cayó en buena tierra, y dio fruto, cuál a ciento, cuál a sesenta, y cuál a treinta por uno.', desc:'La Palabra de Dios cae en diferentes tipos de corazones. Solo el corazón receptivo y perseverante produce fruto abundante.' },
    { nombre:'Las Diez Vírgenes', ref:'Mateo 25:13', txt:'Velad, pues, porque no sabéis el día ni la hora en que el Hijo del Hombre ha de venir.', desc:'Llamado a estar preparados para la venida de Cristo. Cinco vírgenes prudentes con aceite listo; cinco necias sin aceite.' },
  ],
  Reyes: [
    { nombre:'Saúl', ref:'1 Samuel 15:22', txt:'La obediencia es mejor que los sacrificios, y el prestar atención que la grosura de los carneros.', desc:'Primer rey de Israel. Comenzó bien pero su desobediencia y orgullo lo llevaron al rechazo de Dios. Reinó ~1020–1000 a.C.' },
    { nombre:'David', ref:'1 Samuel 13:14', txt:'Jehová se ha buscado un varón conforme a su corazón, al cual Jehová ha designado para que sea príncipe sobre su pueblo.', desc:'Rey pastor, poeta y guerrero. Venció a Goliat, escribió gran parte de los Salmos y estableció Jerusalén como capital.' },
    { nombre:'Salomón', ref:'1 Reyes 3:9', txt:'Da, pues, a tu siervo corazón entendido para juzgar a tu pueblo, y para discernir entre lo bueno y lo malo.', desc:'El rey más sabio. Construyó el Templo de Jerusalén. Sus escritos incluyen Proverbios, Eclesiastés y Cantares.' },
    { nombre:'Ezequías', ref:'2 Reyes 18:5-6', txt:'En Jehová Dios de Israel puso su esperanza; ni después ni antes de él hubo otro como él entre todos los reyes de Judá.', desc:'Rey reformador que destruyó la idolatría. Dios libró a Jerusalén del ejército asirio de Senaquerib en respuesta a su oración.' },
    { nombre:'Josías', ref:'2 Crónicas 34:31', txt:'Y el rey se puso en pie en su lugar, e hizo pacto delante de Jehová de caminar en pos de Jehová.', desc:'Comenzó a reinar a los 8 años. Al hallar el libro de la Ley renovó el pacto con Dios. El gran rey reformador de Judá.' },
    { nombre:'Roboam', ref:'1 Reyes 12:14', txt:'Mi padre agravó vuestro yugo, pero yo añadiré a vuestro yugo; mi padre os castigó con azotes, mas yo os castigaré con escorpiones.', desc:'Hijo de Salomón. Su arrogancia provocó la división del reino en Israel (norte) y Judá (sur) alrededor del 930 a.C.' },
  ],
  Evangelios: [
    { nombre:'Mateo', ref:'Mateo 5:17', txt:'No penséis que he venido para abrogar la ley o los profetas; no he venido para abrogar, sino para cumplir.', desc:'Escrito para judíos. Presenta a Jesús como el Rey Mesías. Contiene el Sermón del Monte (Mt 5-7) y las enseñanzas del Reino.' },
    { nombre:'Marcos', ref:'Marcos 1:1', txt:'El principio del evangelio de Jesucristo, Hijo de Dios.', desc:'El evangelio de la acción. Escrito para romanos. Presenta a Jesús como Siervo activo. El más breve de los cuatro evangelios.' },
    { nombre:'Lucas', ref:'Lucas 19:10', txt:'Porque el Hijo del Hombre vino a buscar y a salvar lo que se había perdido.', desc:'Escrito por un médico. Énfasis en la humanidad de Jesús, la oración, el Espíritu Santo y los marginados de la sociedad.' },
    { nombre:'Juan', ref:'Juan 20:31', txt:'Pero éstas se han escrito para que creáis que Jesús es el Cristo, el Hijo de Dios, y para que creyendo, tengáis vida en su nombre.', desc:'El evangelio teológico. 7 señales y 7 declaraciones "YO SOY". Escrito para que todos crean y tengan vida eterna.' },
    { nombre:'Sermón del Monte', ref:'Mateo 5:3', txt:'Bienaventurados los pobres en espíritu, porque de ellos es el reino de los cielos.', desc:'Las 9 Bienaventuranzas y las enseñanzas centrales del Reino: oración modelo, ayuno, perdón y confianza en Dios. Mt 5-7.' },
    { nombre:'La Última Cena', ref:'Lucas 22:19-20', txt:'Esto es mi cuerpo, que por vosotros es dado; haced esto en memoria de mí... Esta copa es el nuevo pacto en mi sangre.', desc:'Jesús instituyó la Santa Cena la noche antes de su crucifixión. Lavó los pies de sus discípulos y oró por todos los creyentes.' },
  ],
  Héroes: [
    { nombre:'Abraham', ref:'Génesis 15:6', txt:'Y creyó a Jehová, y le fue contado por justicia.', desc:'Padre de la fe. Dejó todo por obediencia. Dios lo probó con Isaac en Moriah. Antepasado de las tres grandes religiones monoteístas.' },
    { nombre:'Moisés', ref:'Éxodo 3:10', txt:'Ven, por tanto, ahora, y te enviaré a Faraón, para que saques a mi pueblo los hijos de Israel de Egipto.', desc:'Libertador de Israel. Las 10 plagas, el paso del Mar Rojo, los 40 años en el desierto y la Ley en el Sinaí.' },
    { nombre:'José', ref:'Génesis 50:20', txt:'Vosotros pensasteis mal contra mí, mas Dios lo encaminó a bien, para hacer lo que vemos hoy.', desc:'De esclavo y preso a gobernador de Egipto. Su historia prefigura a Cristo: rechazado, exaltado y salvador de su pueblo.' },
    { nombre:'Rut', ref:'Rut 1:16', txt:'No me ruegues que te deje, y me aparte de ti; porque a dondequiera que tú fueres, iré yo.', desc:'Fidelidad y redención. Moabita que eligió al pueblo de Dios. Bisabuela del rey David. Modelo de lealtad y amor leal.' },
    { nombre:'Ester', ref:'Ester 4:14', txt:'¿Y quién sabe si para esta hora has llegado al reino?', desc:'Reina judía que arriesgó su vida para salvar a su pueblo del exterminio planificado por Amán. Valentía y propósito divino.' },
    { nombre:'Pablo', ref:'Filipenses 4:13', txt:'Todo lo puedo en Cristo que me fortalece.', desc:'De perseguidor a apóstol. Tras su encuentro con Cristo en el camino a Damasco recorrió el mundo mediterráneo predicando el evangelio.' },
  ],
  'Espíritu Santo': [
    { nombre:'Pentecostés', ref:'Hechos 2:1-4', txt:'Y fueron todos llenos del Espíritu Santo, y comenzaron a hablar en otras lenguas, según el Espíritu les daba que hablasen.', desc:'50 días después de la resurrección. El Espíritu descendió como lenguas de fuego. Nacimiento de la Iglesia. 3.000 convertidos.' },
    { nombre:'Frutos del Espíritu', ref:'Gálatas 5:22-23', txt:'Mas el fruto del Espíritu es: amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza.', desc:'El carácter de Cristo formado en el creyente por el Espíritu. No son logros humanos sino frutos de vida rendida a Dios.' },
    { nombre:'Dones espirituales', ref:'1 Corintios 12:7', txt:'Pero a cada uno le es dada la manifestación del Espíritu para provecho.', desc:'Dones variados: sabiduría, ciencia, fe, sanidades, milagros, profecía, lenguas. Todos para edificar el cuerpo de Cristo.' },
    { nombre:'El Consolador', ref:'Juan 14:16-17', txt:'Y yo rogaré al Padre, y os dará otro Consolador, para que esté con vosotros para siempre: el Espíritu de verdad.', desc:'Jesús prometió enviar al Espíritu Santo como Consolador, Ayudador y Guía que permanece con los creyentes para siempre.' },
    { nombre:'La paloma', ref:'Mateo 3:16', txt:'Y Jesús, después que fue bautizado, subió luego del agua; y he aquí los cielos le fueron abiertos, y vio al Espíritu de Dios que descendía como paloma.', desc:'En el bautismo de Jesús el Espíritu descendió como paloma y el Padre habló desde el cielo. La Trinidad manifestada.' },
  ],
}

export const TEMAS = [
  { icon:'📜', label:'Profetas' },
  { icon:'🎵', label:'Salmos' },
  { icon:'✨', label:'Milagros' },
  { icon:'🙏', label:'Parábolas' },
  { icon:'👑', label:'Reyes' },
  { icon:'📖', label:'Evangelios' },
  { icon:'⚓', label:'Héroes' },
  { icon:'🕊️', label:'Espíritu Santo' },
]

export const ALABANZAS_SUGERIDAS = [
  { titulo:'Renuévame', artista:'Marcos Witt', query:'Marcos Witt Renuévame' },
  { titulo:'Cuán grande es Él', artista:'Hillsong', query:'Hillsong Cuán grande es Él español' },
  { titulo:'Oceans (Océanos)', artista:'Hillsong United', query:'Hillsong United Océanos español' },
  { titulo:'Way Maker', artista:'Sinach', query:'Way Maker Sinach español' },
  { titulo:'Eres Todo Poderoso', artista:'Generación 12', query:'Generación 12 Eres Todo Poderoso' },
  { titulo:'10,000 Razones', artista:'Matt Redman', query:'10000 Razones Matt Redman español' },
  { titulo:'Soy Libre', artista:'Hillsong', query:'Hillsong Soy Libre' },
  { titulo:'Te Alabo', artista:'Jesús Adrián Romero', query:'Jesús Adrián Romero Te Alabo' },
  { titulo:'Sublime Gracia', artista:'Tradicional', query:'Sublime Gracia himno cristiano' },
  { titulo:'Buen Pastor', artista:'Elevation Worship', query:'Elevation Worship Buen Pastor español' },
  { titulo:'Sé Tú Mi Visión', artista:'Tradicional', query:'Sé Tú Mi Visión himno cristiano' },
  { titulo:'Poderoso Eres Tú', artista:'Marcos Witt', query:'Marcos Witt Poderoso Eres Tú' },
  { titulo:'Dios de lo Imposible', artista:'Generación 12', query:'Generación 12 Dios de lo Imposible' },
  { titulo:'Glorioso', artista:'Marcos Witt', query:'Marcos Witt Glorioso' },
  { titulo:'Rey de Reyes', artista:'Hillsong', query:'Hillsong Rey de Reyes español' },
  { titulo:'El Poder de Tu Amor', artista:'Geoff Bullock', query:'El Poder de Tu Amor cristiano' },
]
